# Generated by Django 3.0.3 on 2020-07-21 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20200721_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexad',
            name='Adimage',
            field=models.ImageField(blank=True, null=True, upload_to='indexAd', verbose_name='首页头部广告'),
        ),
    ]
