# Generated by Django 3.0.3 on 2020-07-21 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_indexad_adimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='IndexAd',
            name='seckill_time',
            field=models.DateTimeField(blank=True, help_text='秒杀截止时间', null=True, verbose_name='秒杀截止时间'),
        ),
    ]
