# Generated by Django 3.0.3 on 2020-07-21 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_auto_20200721_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='IndexAd',
            name='seckill_time',
            field=models.DateTimeField(blank=True, help_text='秒杀截止时间v', null=True, verbose_name='秒杀截止时间'),
        ),
    ]
