# Generated by Django 3.0.3 on 2020-07-22 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0005_auto_20200721_1919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indexad',
            name='Adimage',
        ),
        migrations.RemoveField(
            model_name='indexad',
            name='seckill_time',
        ),
        migrations.AddField(
            model_name='goods',
            name='is_pop',
            field=models.BooleanField(default=False, verbose_name='是否推广'),
        ),
        migrations.AddField(
            model_name='goodscategorybrand',
            name='hot_brand',
            field=models.BooleanField(default=False, verbose_name='是否热门'),
        ),
    ]
