# Generated by Django 3.0.3 on 2020-07-23 13:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='verifycode',
            options={'verbose_name': '邮件验证码', 'verbose_name_plural': '邮件验证码'},
        ),
        migrations.RemoveField(
            model_name='verifycode',
            name='mobile',
        ),
        migrations.AddField(
            model_name='verifycode',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=100, verbose_name='电话号码'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(default='', max_length=100, verbose_name='电子邮箱'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='mobile',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='电话号码'),
        ),
    ]
